name: Build Fifteen Puzzle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Устанавливаем CMake
    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      shell: cmd

    # 3. Устанавливаем vcpkg и SFML с диагностикой
    - name: Install vcpkg and SFML
      run: |
        echo "Cloning vcpkg..."
        git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
        cd C:\vcpkg
        echo "Running bootstrap..."
        bootstrap-vcpkg.bat || (echo "vcpkg bootstrap failed!" && exit 1)
        echo "Installing SFML..."
        vcpkg.exe install sfml:x64-windows --recurse || (echo "SFML installation failed!" && exit 1)
        vcpkg.exe integrate install
      shell: cmd

    # 4. Проверяем, что SFML установлен
    - name: Verify SFML installation
      run: |
        echo "Checking SFML installation..."
        dir C:\vcpkg\installed\x64-windows\lib
        if exist C:\vcpkg\installed\x64-windows\lib\sfml-graphics.lib (echo "SFML installed!") else (exit 1)
      shell: cmd

    # 5. Конфигурируем CMake
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
      shell: cmd

    # 6. Компилируем проект
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release
      shell: cmd

    # 7. Проверяем, что исполняемый файл создан
    - name: Check for executable
      run: |
        if exist build\Release\FifteenPuzzle.exe (echo "Build successful!") else (exit 1)
      shell: cmd

    # 8. Загружаем артефакт
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FifteenPuzzle-Windows
        path: build/Release/FifteenPuzzle.exe
        if-no-files-found: error
