name: Build Fifteen Puzzle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Проверяем наличие CMakeLists.txt
    - name: Check for CMakeLists.txt
      run: |
        dir CMakeLists.txt
        if exist CMakeLists.txt (echo "CMakeLists.txt found!") else (echo "CMakeLists.txt not found!" && exit 1)
      shell: cmd

    # 3. Устанавливаем CMake
    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      shell: cmd

    # 4. Кэшируем vcpkg
    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: C:\vcpkg
        key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
        restore-keys: vcpkg-${{ runner.os }}-

    # 5. Устанавливаем vcpkg и SFML
    - name: Install vcpkg and SFML
      run: |
        if not exist C:\vcpkg (
          echo "Cloning vcpkg..."
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          cd C:\vcpkg
          .\bootstrap-vcpkg.bat
        ) else (
          echo "vcpkg already exists, checking for vcpkg.exe..."
          cd C:\vcpkg
          if not exist vcpkg.exe (
            echo "vcpkg.exe not found, running bootstrap-vcpkg.bat..."
            .\bootstrap-vcpkg.bat
          ) else (
            echo "vcpkg.exe found!"
          )
        )
        cd C:\vcpkg
        .\vcpkg.exe install sfml:x64-windows --recurse --clean-after-build
        .\vcpkg.exe integrate install
      shell: cmd

    # 6. Диагностика: Проверяем, установлена ли SFML
    - name: Check SFML installation
      run: |
        dir C:\vcpkg\installed\x64-windows\lib
        if exist C:\vcpkg\installed\x64-windows\lib\sfml-graphics.lib (echo "SFML installed!") else (echo "SFML not installed!" && exit 1)
      shell: cmd

    # 7. Конфигурируем CMake
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ../ -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_STANDARD=20
      shell: cmd

    # 8. Компилируем проект
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release
      shell: cmd

    # 9. Диагностика: Проверяем структуру директорий
    - name: Debug directory structure
      run: |
        dir build
        dir build\Release
      shell: cmd

    # 10. Диагностика: Проверяем, существует ли файл
    - name: Check for executable
      run: |
        if exist build\Release\FifteenPuzzle.exe (echo "Executable found!") else (echo "Executable not found!")
      shell: cmd

    # 11. Загружаем артефакт
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FifteenPuzzle-Windows
        path: build/Release/FifteenPuzzle.exe
        if-no-files-found: warn