name: Build Fifteen Puzzle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      shell: cmd

    # Установка vcpkg
    - name: Install vcpkg
      run: |
        echo "Cloning vcpkg..."
        git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
        cd C:\vcpkg
        echo "Bootstrapping vcpkg..."
        bootstrap-vcpkg.bat || (echo "vcpkg bootstrap failed!" && exit 1)
      shell: cmd

    # Установка SFML
    - name: Install SFML
      run: |
        echo "Installing SFML..."
        C:\vcpkg\vcpkg.exe install sfml:x64-windows --recurse || (echo "SFML installation failed!" && exit 1)
        C:\vcpkg\vcpkg.exe integrate install
      shell: cmd

    # Проверка структуры vcpkg
    - name: Debug vcpkg directories
      run: |
        echo "Checking vcpkg structure..."
        dir C:\vcpkg
        dir C:\vcpkg\installed
        dir C:\vcpkg\installed\x64-windows || echo "Directory x64-windows NOT FOUND!"
        dir C:\vcpkg\installed\x64-windows\lib || echo "Library folder NOT FOUND!"
      shell: cmd

    # Проверяем, что SFML установлен
    - name: Verify SFML installation
      run: |
        if exist C:\vcpkg\installed\x64-windows\lib\sfml-graphics.lib (echo "SFML installed!") else (echo "SFML NOT FOUND!" && exit 1)
      shell: cmd

    # Конфигурируем CMake
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
      shell: cmd

    # Компиляция
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release
      shell: cmd

    # Проверка наличия исполняемого файла
    - name: Check for executable
      run: |
        if exist build\Release\FifteenPuzzle.exe (echo "Build successful!") else (exit 1)
      shell: cmd

    # Загрузка артефакта
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FifteenPuzzle-Windows
        path: build/Release/FifteenPuzzle.exe
        if-no-files-found: error
